# Generated by Django 5.1.7 on 2025-04-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('entrance_fee', models.FloatField(blank=True, null=True)),
                ('best_time_to_visit', models.CharField(max_length=200)),
                ('significance', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
