# Generated by Django 5.1.7 on 2025-04-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_place_delete_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('locality', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('cuisine', models.CharField(max_length=255)),
                ('rating', models.FloatField(default=0.0)),
                ('votes', models.IntegerField(default=0)),
                ('cost', models.FloatField(default=0.0)),
            ],
        ),
    ]
